### ISSUE TITLE
Error on saving a filterscheme containing an enum

### ISSUE THREAD

**Issue by half-evil** [WildGums/Orc.FilterBuilder#169]
Hi WildGums-Team,

thank you for this useful component. I'm getting an exception ```The '`' character, hexadecimal value 0x60, cannot be included in a name.``` when I try to save/serialize a filterscheme that contains a rule based on an enum value. 
My example rule ToString is `Movement is equal to 'B1'` with the enum definition
``` 
public enum Movement : byte
{
    B1 = 0,
    B2 = 1
}
```
The exception gets thrown by calling `Catel.Runtime.Serialization.Xml.XmlSerializer.Serialize(path, memoryStream)` or `FilterSerializationService.SaveFiltersAsync(path)`.

I've found this issue https://github.com/Catel/Catel/issues/1073 of Catel.Core v4. Maybe they are related.

Also an existing xml-file gets overwritten/deleted, if the serialization fails. Please can you change this behaviour, that the file gets only overwritten, when the serialization succeeds?

Platform: Win 10
.NET version: 4.6.1 and Core 3
FilterBuilder 3.1.1, Catel.Core 5.10.0 and 5.11.2

**Comment by GeertvanHorrik** [comment]
Can you please try the latest prerelease (alpha) to see if that fixes the issue?

**Comment by half-evil** [comment]
The bug still exists in FilterBuilder v3.2alpha-0277. 
With Catel.Core v5.12.0-beta0006 I was able to write the filterschemes to a xml-file. But now `fSchemes.LoadFiltersAsync(xmlpath)` doesn't return anything and no exception is thrown. The task doesn't complete anymore. 

Here is the xml of the filterscheme:
```
<FilterScheme ctl:graphid="12" xmlns:d0p0="http://schemas.datacontract.org/2004/07/Orc.FilterBuilder.Models" i:type="d0p0:FilterScheme">
      <TargetType ctl:type="System.String">OSPH.Isomed.Lib.DataPoint</TargetType>
      <Title>Nur Isokinetische Phase</Title>
      <FilterGroup ctl:IsNull="true" />
      <HasInvalidConditionItems>False</HasInvalidConditionItems>
      <ConditionItems ctl:graphid="13">
        <ConditionGroup ctl:graphid="14" xmlns:d0p0="http://schemas.datacontract.org/2004/07/Orc.FilterBuilder" i:type="d0p0:ConditionGroup">
          <Type>And</Type>
          <Items ctl:graphid="15">
            <PropertyExpression ctl:graphid="16" i:type="d0p0:PropertyExpression">
              <Property ctl:type="System.String">OSPH.Isomed.Lib.DataPoint||Phase</Property>
              <DataTypeExpression ctl:graphid="17" ctl:type="Orc.FilterBuilder.EnumExpression`1[[OSPH.Isomed.Lib.Phase]]">
                <Value>Isokinetic</Value>
                <IsNullable>False</IsNullable>
                <SelectedCondition>EqualTo</SelectedCondition>
                <IsValueRequired>True</IsValueRequired>
                <ValueControlType>Enum</ValueControlType>
              </DataTypeExpression>
              <Items ctl:graphid="18" />
            </PropertyExpression>
            <PropertyExpression ctl:graphid="19" i:type="d0p0:PropertyExpression">
              <Property ctl:type="System.String">OSPH.Isomed.Lib.DataPoint||Movement</Property>
              <DataTypeExpression ctl:graphid="20" ctl:type="Orc.FilterBuilder.EnumExpression`1[[OSPH.Isomed.Lib.Movement]]">
                <Value>B1</Value>
                <IsNullable>False</IsNullable>
                <SelectedCondition>EqualTo</SelectedCondition>
                <IsValueRequired>True</IsValueRequired>
                <ValueControlType>Enum</ValueControlType>
              </DataTypeExpression>
              <Items ctl:graphid="21" />
            </PropertyExpression>
          </Items>
        </ConditionGroup>
      </ConditionItems>
    </FilterScheme>
```

**Comment by GeertvanHorrik** [comment]
Could you please create a repro / share your code so we can implement this as a unit test? We made some improvements to the serialization engine in Catel (beta 7) today, but want to test it.

**Comment by half-evil** [comment]
Sorry for being so late. Here is my repo https://github.com/half-evil/FilterSchemeTests with a unit test of my save function. 
With your new version 3.2.0 of FilterBuilder I get this error:
`    System.Runtime.Serialization.SerializationException : Type 'Orc.FilterBuilder.ConditionGroup' with data contract name 'ConditionGroup:http://schemas.datacontract.org/2004/07/Orc.FilterBuilder' is not expected. Add any types not known statically to the list of known types - for example, by using the KnownTypeAttribute attribute or by adding them to the list of known types passed to DataContractSerializer.`

## Libs
Catel.Core 5.12.1-beta0262
Orc.FilterBuilder 3.2
Orc.Metadata 3.2
System.ComponentModel.Annotations 4.6 or 4.7
