### ISSUE TITLE
Getting an error on saving a filterscheme containing an enum

### ISSUE THREAD

**Issue by half-evil** [WildGums/Orc.FilterBuilder#210]
Sorry for reopening this issue. I couldn't work lately on the project which uses your lib and my original issue (https://github.com/WildGums/Orc.FilterBuilder/issues/169#) has been closed by a bot.
Here is my repo https://github.com/half-evil/FilterSchemeTests with some unit tests of my save function.
With your new version 3.3.0 of FilterBuilder all tests fail with this error:
>System.Runtime.Serialization.SerializationException : Type 'Orc.FilterBuilder.ConditionGroup' with data contract name 'ConditionGroup:http://schemas.datacontract.org/2004/07/Orc.FilterBuilder' is not expected. Add any types not known statically to the list of known types - for example, by using the KnownTypeAttribute attribute or by adding them to the list of known types passed to DataContractSerializer.

I hope that i'm using your lib the right way.
Thank you for your help.

## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [x] WPF
 - [ ] UWP
 - [ ] iOS
 - [ ] Android
 - [ ] .NET Standard
 - [ ] .NET Core

## Component
FilterSchemes
XmlSerializer

## Version of Library
Catel.Core 5.12.5
Orc.FilterBuilder 3.3
Orc.Metadata 3.2
System.ComponentModel.Annotations 4.7

## Version of OS(s) listed above with issue
Win 10

## Steps to Reproduce
1.
2.
3.

## Actual Behavior

**Comment by GeertvanHorrik** [comment]
Moving over unit tests to Orc.FilterBuilder project.

**Comment by GeertvanHorrik** [comment]
Investigating a fix in Catel to support abstract items in a collection being used in serialization. Not sure why this doesn't fail for any of the other tests we have (probably because the example has an empty ConditionGroup).

**Comment by GeertvanHorrik** [comment]
Good news! I've improved support for (de)serializing abstract members in Catel and it seems to work great now with your unit tests:

![image](https://user-images.githubusercontent.com/1246444/85128139-024d8d80-b231-11ea-9432-7cf9ba96f107.png)

Will try to release ASAP.

**Comment by GeertvanHorrik** [comment]
Closing this ticket, feel free to re-open when it's not working for you.
