### ISSUE TITLE
Feature Request: Ability to use the control without the Window

### ISSUE THREAD

**Issue by maciz84** [WildGums/Orc.FilterBuilder#24]
It would be great to be able to use the filter control without the need for a window like below.

![preview](https://cloud.githubusercontent.com/assets/20792882/17330964/e2580fc8-58c0-11e6-8298-a22507b24a07.png)

The idea is to have the ability to have a layout like the window image below but directly in your user control. The image below is using another 3rd party control (ignore styling) which has this ability built in

![captureidea](https://cloud.githubusercontent.com/assets/20792882/17331145/9938417c-58c1-11e6-9086-25c30950f2a9.PNG)

**Comment by GeertvanHorrik** [comment]
I have pushed the control. Note that you need to set the data context of the `EditFilterView` to an instance of `FilterSchemeEditInfo`. Then it should work.

**Comment by GeertvanHorrik** [comment]
Build - 1.6.0-unstable.67
