### ISSUE TITLE
Latest Orc.FilterBuilder does not respect runtime metadata

### ISSUE THREAD

**Issue by GeertvanHorrik** [WildGums/Orc.FilterBuilder#32]
We use runtime metadata a lot in our apps, but PR #27 seems to break things. This could be caused by the linq expressions always using a property and not respecting the runtime metadata.

@alexis- / @mkhomutov , what are your thoughts?

**Comment by mkhomutov** [comment]
well, the thoughts are simple. I could provide unit tests for it, but before we have to roll back the changes

**Comment by GeertvanHorrik** [comment]
Please revert for now and provide unit tests so @alexis- can look at it.

**Comment by mkhomutov** [comment]
reverted

**Comment by alexis-** [comment]
Yes, please do provide some samples so I can fix this issue.

I have been investigating Orc.Metadata (I am fond of the idea you suggested in issue #30 ) and working on an extension (will communicate with you about it soon), so hopefully I may have a better insight on the causes of your issue.

Alex.
