### ISSUE TITLE
Installed via NuGet -> file could not be loaded

### ISSUE THREAD

**Issue by nadilas** [WildGums/Orc.FilterBuilder#34]
Window cannot be displayed.

### Steps to reproduce

1. Install via NuGet (v1.6.0)
2. Reference assembly: `xmlns:views="clr-namespace:Orc.FilterBuilder.Views;assembly=Orc.FilterBuilder"`
3. Use Control: `<views:FilterBuilderControl RawCollection="{Binding RawItems}" FilteredCollection="{Binding FilteredItems}" />`
4. Start application
5. On load window XamlParseException

Platform:
.NET version: 4.5

### Expected behaviour

Window should load normally.

### Actual behaviour

XamlParseException:
Additional information: Could not load file or assembly 'Orc.FilterBuilder, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.

#### Update:
The setup I have is, that I have a class library, which pulls the FilterBuilder package. When this class library project is built, due to Copy to Local=true, the .dll gets copied to the output directory. However, in the WPF Project where I reference this class library, FilterBuilder does not appear. Other nuget packages are by default visible e.g. in the ClickOnce publish (application files) window. Strangely FilterBuilder and Catel don't make the list. Both the class library and the WPF project have the same .NET version defined.

Any ideas?

**Comment by GeertvanHorrik** [comment]
Thanks for the report. We will look into this.

**Comment by GeertvanHorrik** [comment]
@mkhomutov or @michu , who wants to look into this one?

**Comment by michu** [comment]
Good morning,

I tried to reproduce with "WPF Application with Catel" template without success.
@nadilas Are you sure that all dependencies are installed (Catel.Core and Catel.MVVM) ?

**Comment by mkhomutov** [comment]
Catel.Core and Catel.MVVM should be installed automatically when you installed Orc.FilterBuilder
going to try to reproduce it step by step as described

**Comment by mkhomutov** [comment]
works fine for me. No exceptions

**Comment by nadilas** [comment]
@michu sorry I didn't check back for a while. Yes both core and MVVM were intalled at the time.

**Comment by GeertvanHorrik** [comment]
@nadilas if this problem is still active, please provide a simple repro since we cannot reproduce it. Thanks!
