### ISSUE TITLE
Better example and usage info would be nice

### ISSUE THREAD

**Issue by durato** [WildGums/Orc.FilterBuilder#35]
Hello,

I've been trying to get this working for a while, without success. I downloaded and built the dev repo, ran Example and the ribbon-based solution is working well.
But when I tried to include it as the readme/tutorial said, I only got a Button with caption "Default". I saw that @maciz84 and @GeertvanHorrik been talking about the same use case I might need (however, my aim is to provide a standalone filter control for my WPF app).

Could you please:
1) provide a really basic example of this control opening in a window/above a dataGrid?
2) add clarification to readme, because for me it's quite obvious that instead of "Import namespace, add control and done" method, I must provide lots of code-behind to be able to use this otherwise fantastic control.

I tried with VS2013 and 2015 as well, through nuGet and also building the project locally and including the built dll. Also tried using "WPF with catel" template, no success either way.

Thanks in advance

**Comment by GeertvanHorrik** [comment]
I'm sorry, but we don't have the resources to create more examples than we have right now. You could try to look into the LogViewer application which also uses most Orc.* components.
