### ISSUE TITLE
User should not be allowed to delete condition when it is only condition in the filter

### ISSUE THREAD

**Issue by auz34** [WildGums/Orc.FilterBuilder#5]
When you delete such condition there is no way to return it back.
![image](https://cloud.githubusercontent.com/assets/3331375/6054986/d9f5a53e-acaa-11e4-983d-ec5cfd92871a.png)

**Comment by GeertvanHorrik** [comment]
You are right. I will put this on the list.

**Comment by GeertvanHorrik** [comment]
This if xied.
